import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import '../models/blood_test.dart';

class PDFService {
  static Future<File> generateReport(BloodTest test) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('dd MMM yyyy, HH:mm');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          // Header
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'AI BloodScan Report',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(
                  dateFormat.format(test.timestamp),
                  style: const pw.TextStyle(fontSize: 12),
                ),
              ],
            ),
          ),

          pw.SizedBox(height: 20),

          // Complete Blood Count Table
          pw.Text(
            'Complete Blood Count (CBC)',
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),

          _buildParametersTable(test),

          pw.SizedBox(height: 20),

          // Diagnosis Section
          pw.Text(
            'Analysis & Diagnosis',
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 10),

          _buildDiagnosisSection(test),

          pw.SizedBox(height: 30),

          // Disclaimer
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.grey300,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
            ),
            child: pw.Text(
              'DISCLAIMER: This report is generated by AI and is for informational purposes only. Please consult a qualified healthcare provider for proper medical diagnosis and treatment.',
              style: const pw.TextStyle(fontSize: 10),
            ),
          ),
        ],
      ),
    );

    // Save PDF
    final output = await getTemporaryDirectory();
    final file = File('${output.path}/blood_test_report_${test.timestamp.millisecondsSinceEpoch}.pdf');
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  static pw.Widget _buildParametersTable(BloodTest test) {
    final params = test.getAllParameters();
    final List<List<String>> tableData = [];

    params.forEach((name, value) {
      final analysis = test.diagnosis[name];
      final status = analysis?['status'] ?? 'N/A';
      final range = analysis?['range'] ?? 'N/A';

      tableData.add([
        name,
        value.toStringAsFixed(2),
        range,
        status,
      ]);
    });

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey400),
      children: [
        // Header
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.grey300),
          children: [
            _buildTableCell('Parameter', isHeader: true),
            _buildTableCell('Value', isHeader: true),
            _buildTableCell('Reference Range', isHeader: true),
            _buildTableCell('Status', isHeader: true),
          ],
        ),
        // Data rows
        ...tableData.map((row) => pw.TableRow(
          children: row.map((cell) => _buildTableCell(cell)).toList(),
        )),
      ],
    );
  }

  static pw.Widget _buildTableCell(String text, {bool isHeader = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(5),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontWeight: isHeader ? pw.FontWeight.bold : pw.FontWeight.normal,
          fontSize: isHeader ? 12 : 10,
        ),
      ),
    );
  }

  static pw.Widget _buildDiagnosisSection(BloodTest test) {
    final overall = test.diagnosis['overall'];
    final assessment = overall?['assessment'] ?? 'No assessment available';
    final conditions = overall?['conditions'] as List? ?? [];

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Overall Assessment:',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
        ),
        pw.SizedBox(height: 5),
        pw.Text(assessment, style: const pw.TextStyle(fontSize: 12)),
        
        if (conditions.isNotEmpty) ...[
          pw.SizedBox(height: 10),
          pw.Text(
            'Potential Conditions:',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 5),
          ...conditions.map((c) => pw.Bullet(text: c.toString())),
        ],
      ],
    );
  }

  static Future<void> shareReport(File pdfFile) async {
    await Share.shareXFiles(
      [XFile(pdfFile.path)],
      subject: 'Blood Test Report',
      text: 'Here is my blood test report from AI BloodScan',
    );
  }

  static Future<void> printReport(File pdfFile) async {
    final data = await pdfFile.readAsBytes();
    await Printing.layoutPdf(onLayout: (format) async => data);
  }
}
